// GENERATED by scripts/prepare-project-images.mjs. Do not edit by hand.
// Real screenshots only (personal data pixelated). Projects with an empty list show labelled CONCEPT tiles.
export interface Screenshot {
  src: string
  tile: string
  alt: string
  caption: string
  title: string
  role: 'hero' | 'support' | 'detail'
  width: number
  height: number
  redacted: boolean
}

export interface Logo {
  src: string
  alt: string
  owner: string
  width: number
  height: number
}

export const screenshots: Record<'yamini' | 'kavya' | 'uzhavan', Screenshot[]> = {
  "yamini": [
    {
      "src": "/projects/yamini/yamini-gps-live-tracking.webp",
      "tile": "/projects/yamini/yamini-gps-live-tracking-tile.webp",
      "alt": "Yamini Infotech admin app, Live Tracking page: field-team list, satellite map and a per-employee status panel (employee identities pixelated)",
      "caption": "LIVE TRACKING · FIELD TEAM, MAP AND STATUS PANEL",
      "title": "Live tracking",
      "role": "hero",
      "width": 2000,
      "height": 1087,
      "redacted": true
    },
    {
      "src": "/projects/yamini/yamini-attendance.webp",
      "tile": "/projects/yamini/yamini-attendance-tile.webp",
      "alt": "Yamini Infotech admin app, Attendance Management page: on-time, late and absent counts with a per-employee table (employee names pixelated)",
      "caption": "ATTENDANCE MANAGEMENT · STATUS PER EMPLOYEE",
      "title": "Attendance",
      "role": "detail",
      "width": 2000,
      "height": 1087,
      "redacted": true
    },
    {
      "src": "/projects/yamini/yamini-erp-dashboard.webp",
      "tile": "/projects/yamini/yamini-erp-dashboard-tile.webp",
      "alt": "Yamini Infotech admin app dashboard: enquiries, complaints, salesmen and revenue cards with recent enquiries and service escalations (customer names pixelated)",
      "caption": "ERP DASHBOARD · ENQUIRIES AND SERVICE ESCALATIONS",
      "title": "ERP dashboard",
      "role": "support",
      "width": 2000,
      "height": 1087,
      "redacted": true
    }
  ],
  "kavya": [
    {
      "src": "/projects/kavya/kavya-fleet-live-tracking.webp",
      "tile": "/projects/kavya/kavya-fleet-live-tracking-tile.webp",
      "alt": "Kavya Transports fleet-management app, Live Tracking page: vehicle list, map of vehicle positions across South India and a vehicle detail panel (vehicle registrations pixelated)",
      "caption": "FLEET TRACKING · VEHICLE LIST, MAP AND DETAIL PANEL",
      "title": "Fleet tracking",
      "role": "hero",
      "width": 2000,
      "height": 1087,
      "redacted": true
    },
    {
      "src": "/projects/kavya/kavya-fleet-dashboard.webp",
      "tile": "/projects/kavya/kavya-fleet-dashboard-tile.webp",
      "alt": "Kavya Transports fleet-management app dashboard: vehicles, active trips, drivers and pending LRs with suggested actions",
      "caption": "FLEET DASHBOARD · VEHICLES, TRIPS, DRIVERS",
      "title": "Fleet dashboard",
      "role": "support",
      "width": 2000,
      "height": 1087,
      "redacted": false
    },
    {
      "src": "/projects/kavya/kavya-vehicles.webp",
      "tile": "/projects/kavya/kavya-vehicles-tile.webp",
      "alt": "Kavya Transports fleet-management app, Vehicles page: vehicle list with make, type, ownership, status and odometer (registration numbers pixelated)",
      "caption": "VEHICLES · FLEET MASTER LIST",
      "title": "Vehicles",
      "role": "support",
      "width": 2000,
      "height": 1087,
      "redacted": true
    }
  ],
  "uzhavan": []
}

export const logos: Record<'yamini' | 'kavya' | 'uzhavan' | 'karunya' | 'lifechangersind', Logo> = {
  "yamini": {
    "src": "/logos/yamini.webp",
    "alt": "Yamini Infotech logo",
    "owner": "Yamini Infotech",
    "width": 256,
    "height": 256
  },
  "kavya": {
    "src": "/logos/kavya.webp",
    "alt": "Kavya Transports logo",
    "owner": "Kavya Transports",
    "width": 214,
    "height": 256
  },
  "uzhavan": {
    "src": "/logos/uzhavan.webp",
    "alt": "UzhavaAI logo",
    "owner": "UZHAVAN AI",
    "width": 256,
    "height": 256
  },
  "karunya": {
    "src": "/logos/karunya.webp",
    "alt": "Karunya logo",
    "owner": "Karunya Institute of Technology and Sciences",
    "width": 225,
    "height": 225
  },
  "lifechangersind": {
    "src": "/logos/lifechangersind.webp",
    "alt": "LifeChangersInd logo",
    "owner": "LifeChangersInd",
    "width": 200,
    "height": 200
  }
}
